[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sshpilot"
version = "3.8.5"
authors = [
  { name="mFat", email="newmfat@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.9"
description = "SSH connection manager and terminal"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "PyGObject>=3.42",
    "pycairo>=1.20.0",
    "paramiko>=3.4",
    "pysftp==0.2.9",
    "cryptography>=42.0",
    "keyring>=24.3",
    "psutil>=5.9.0",
]

[tool.setuptools.packages.find]
where = ["", "src"]
include = ["sshpilot*", "sshpilot_dnd*"]
exclude = ["packaging*", "screenshots*"]
[project.urls]
Homepage = "https://github.com/mfat/sshpilot"
Issues = "https://github.com/mfat/sshpilot/issues"
